version: '3.9'
services:
  allertree:
    container_name: allertree
    image: 'registry.richardx.win/allertree:latest'
    restart: unless-stopped
    ports:
      - '3005'
    labels:
      - traefik.enable=true
      - traefik.http.routers.allertree.rule=Host(`allertree.richardx.win`)
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY

networks:
  default:
    name: proxy
    external: true
